[build]
  command = "cd web && npm ci && npm run build"
  publish = "web/dist"

[build.environment]
  NODE_VERSION = "20"

# Optional: enable Node 18+ build image
[functions]
  node_bundler = "esbuild"

